# Étape 1 : Construction de l'application
FROM node:23-alpine AS build

# Définir le répertoire de travail
WORKDIR /app

# Copier package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers de l'application
COPY . .

# Construire l'application React
RUN npm run build

# Étape 2 : Servir l'application
FROM nginx:alpine

# Copier les fichiers de build de l'étape précédente
COPY --from=build /app/build /usr/share/nginx/html

# Exposer le port sur lequel Nginx va écouter
EXPOSE 80

# Démarrer Nginx
CMD ["nginx", "-g", "daemon off;"]
